### ISSUE TITLE
% or # ?

### ISSUE THREAD

**Issue by bitwombat** [nickjj/ansible-user#2]
Hi Nick,

Did you mean for the leading % here?  Because that means "group named", but user_name is not a group name.

````
- name: Enable passwordless sudo
  copy:
    content: '%{{ user_name }} ALL=(ALL) NOPASSWD:ALL'
````

Usually works, except I accidentally nuked my user "app"'s ownership in the group named app and sudo suddenly started asking me for a password.

(I think ansible has a bug with their group module, but that's not your issue).

**Comment by nickjj** [comment]
Hi,

By default when Ansible creates a user, it will also create a group for that user.

If you add custom `user_groups`, your user should end up belonging to all of those custom groups in addition to a group that's equal to the name of the `user_name`.

Example:

```yml
user_groups: ["foo", "bar"]
user_name: "deploy"
```

Will produce something like this on your server:
`uid=1000(deploy) gid=1002(deploy) groups=1002(deploy),1000(foo),1001(bar)`

In which case, `%` should be ok.

What did you exactly do to produce your issue? I know it's been 18 months and Ansible has changed a lot since then.

**Comment by bitwombat** [comment]
Thanks for the reply but that's long slide off the mental stack :)
